/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

/* Include section */
#include <stdio.h>
#include <stdint.h>

/* Define section */
#define SIZE_TASK_STACK          1024U
#define SIZE_SCHED_STACK         1024U

#define SRAM_START               0x20000000U
#define SIZE_SRAM                ((128) * (1024))
#define SRAM_END                 ((SRAM_START) + (SIZE_SRAM))

#define T1_STACK_START           SRAM_END
#define T2_STACK_START           ((SRAM_END) - (1 * SIZE_TASK_STACK))
#define T3_STACK_START           ((SRAM_END) - (2 * SIZE_TASK_STACK))
#define T4_STACK_START           ((SRAM_END) - (3 * SIZE_TASK_STACK))
#define IDLE_STACK_START         ((SRAM_END) - (4 * SIZE_TASK_STACK))
#define SCHED_STACK_START        ((SRAM_END) - (5 * SIZE_TASK_STACK))

#define TICK_HZ 				 1000U
#define HSI_CLOCK         		 16000000U
#define SYSTICK_TIM_CLK   		 HSI_CLOCK

#define MAX_TASKS			     4
#define XPSR_VALUE				 0x01000000
#define LR_VALUE				 0xFFFFFFFD
#define MAX_CORE_REGISTERS       13
#define RX_DUMMY_FRAME_VALUE	 0
#define USGFAULTENA				 18
#define BUSFAULTENA				 17
#define MEMFAULTENA				 16

#define ZERO					 0
#define ONE						 1
#define TWO						 2

/* Function prototypes section*/
void RTOS_task1Handler(void);
void RTOS_task2Handler(void);
void RTOS_task3Handler(void);
void RTOS_task4Handler(void);

void RTOS_initSystickTimer(uint32_t tick_hz);
__attribute__((naked)) void RTOS_initSchedulerStack(uint32_t sched_top_of_stack);
void RTOS_initTasksStack(void);
void RTOS_enableProcessorFaults(void);
__attribute__((naked)) void RTOS_switchToPsp(void);
uint32_t RTOS_getPspValue(void);
void RTOS_setPspValue(uint32_t currentPspAddress);
void RTOS_updateNextTask(void);

/* Global variables section */
uint32_t pspOfTasks[MAX_TASKS] = {T1_STACK_START, T2_STACK_START, T3_STACK_START, T4_STACK_START};
uint32_t taskHandlers[MAX_TASKS];
uint8_t currentTask;

int main(void)
{
	RTOS_enableProcessorFaults();
	taskHandlers[0] = (uint32_t) RTOS_task1Handler;
	taskHandlers[1] = (uint32_t) RTOS_task2Handler;
	taskHandlers[2] = (uint32_t) RTOS_task3Handler;
	taskHandlers[3] = (uint32_t) RTOS_task4Handler;
	RTOS_initSchedulerStack(SCHED_STACK_START);
	RTOS_initSystickTimer(TICK_HZ);
	RTOS_switchToPsp();
	RTOS_initTasksStack();
	/* Start from first task */
	RTOS_task1Handler();
	for(;;);
}

void RTOS_task1Handler(void)
{
	while(1)
	{
		printf("Running task 1\n");
	}
}

void RTOS_task2Handler(void)
{
	while(1)
	{
		printf("Running task 2\n");
	}
}

void RTOS_task3Handler(void)
{
	while(1)
	{
		printf("Running task 3\n");
	}
}

void RTOS_task4Handler(void)
{
	while(1)
	{
		printf("Running task 4\n");
	}
}

void RTOS_initSystickTimer(uint32_t tick_hz)
{
	uint32_t *pSRVR = (uint32_t*)0xE000E014;
	uint32_t *pSCSR = (uint32_t*)0xE000E010;
    /* Calculation of reload value */
    uint32_t count_value = (SYSTICK_TIM_CLK/tick_hz) - 1;
    /* Clear the value of SVR */
    *pSRVR &= ~(0x00FFFFFFFF);
    /* Load the value in to SVR */
    *pSRVR |= count_value;
    /* Enable SysTick exception request */
    *pSCSR |= ( 1 << ONE);
    /* Indicate the clock source: processor clock source */
    *pSCSR |= ( 1 << TWO);
    /* Enable the counter */
    *pSCSR |= ( 1 << ZERO);
}

__attribute__((naked)) void RTOS_initSchedulerStack(uint32_t schedTopOfStack)
{
     __asm volatile("MSR MSP,%0": :  "r" (schedTopOfStack)  :   );
     __asm volatile("BX LR");
}

uint32_t RTOS_getPspValue(void)
{
	return pspOfTasks[currentTask];
}

void RTOS_setPspValue(uint32_t currentPspAddress)
{
	pspOfTasks[currentTask] = currentPspAddress;
}

void RTOS_updateNextTask(void)
{
	/* Round Robin algorithm */
	currentTask++;
	currentTask %= MAX_TASKS;
}

__attribute__((naked)) void RTOS_switchToPsp(void)
{
	/* Save original LR */
	__asm volatile("PUSH {LR}");
	__asm volatile("BL RTOS_getPspValue");
	__asm volatile("MSR PSP, R0");
	__asm volatile("POP {LR}");
	/* Make PSP as default SP */
	__asm volatile("MOV R0, #0X02");
	__asm volatile("MSR CONTROL, R0");
	__asm volatile("BX LR");
}

void RTOS_initTasksStack(void)
{
	uint32_t* pPSP;
	for (uint8_t iTask = 0; iTask < MAX_TASKS; iTask++)
	{
		pPSP = (uint32_t*) pspOfTasks[iTask];
		/* Stack model full descending */
		pPSP--;
		*pPSP = XPSR_VALUE;
		pPSP--;
		*pPSP = (uint32_t) taskHandlers[iTask];
		pPSP--;
		*pPSP = LR_VALUE;

		for (uint8_t iRx = 0; iRx < MAX_CORE_REGISTERS; iRx++)
		{
			pPSP--;
			*pPSP = RX_DUMMY_FRAME_VALUE;
		}
		/* Store the final value of PSP for each task to return them later */
		pspOfTasks[iTask] = (uint32_t) pPSP;
	}
}

__attribute__((naked)) void SysTick_Handler(void)
{
	/* Save the context of current task */
	__asm volatile("MRS R0, PSP");
	__asm volatile("STMDB R0!, {R4-R11}");
	/* Save original LR */
	__asm volatile("PUSH {LR}");
	__asm volatile("BL RTOS_setPspValue");
	/* Retrieve the context of next task */
	__asm volatile("BL RTOS_updateNextTask");
	__asm volatile("BL RTOS_getPspValue");
	__asm volatile("LDMIA R0!, {R4-R11}");
	__asm volatile("MSR PSP, R0");
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");
}

void RTOS_enableProcessorFaults(void)
{
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;
	*pSHCSR |= ( 1 << MEMFAULTENA);
	*pSHCSR |= ( 1 << BUSFAULTENA);
	*pSHCSR |= ( 1 << USGFAULTENA);
}

void HardFault_Handler(void)
{
	printf("Exception : Hardfault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
	while(1);
}
