/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

/* Include section */
#include <stdio.h>
#include <stdint.h>
#include "led.h"

/* Define section */
#define SIZE_TASK_STACK          1024U
#define SIZE_SCHED_STACK         1024U
#define INTERRUPT_DISABLE()  	 do{__asm volatile ("MOV R0,#0x1"); asm volatile("MSR PRIMASK,R0"); } while(0)
#define INTERRUPT_ENABLE()  	 do{__asm volatile ("MOV R0,#0x0"); asm volatile("MSR PRIMASK,R0"); } while(0)

#define SRAM_START               0x20000000U
#define SIZE_SRAM                ((128) * (1024))
#define SRAM_END                 ((SRAM_START) + (SIZE_SRAM))

#define T1_STACK_START           SRAM_END
#define T2_STACK_START           ((SRAM_END) - (1 * SIZE_TASK_STACK))
#define T3_STACK_START           ((SRAM_END) - (2 * SIZE_TASK_STACK))
#define T4_STACK_START           ((SRAM_END) - (3 * SIZE_TASK_STACK))
#define IDLE_STACK_START         ((SRAM_END) - (4 * SIZE_TASK_STACK))
#define SCHED_STACK_START        ((SRAM_END) - (5 * SIZE_TASK_STACK))

#define TICK_HZ 				 1000U
#define HSI_CLOCK         		 16000000U
#define SYSTICK_TIM_CLK   		 HSI_CLOCK
#define TASK_RUNNING_STATE  	 0x00
#define TASK_BLOCKED_STATE  	 0xFF

#define XPSR_VALUE				 0x01000000
#define LR_VALUE				 0xFFFFFFFD
#define MAX_CORE_REGISTERS       13
#define RX_DUMMY_FRAME_VALUE	 0
#define USGFAULTENA				 18
#define BUSFAULTENA				 17
#define MEMFAULTENA				 16
#define PENDSVSET				 28

#define ZERO					 0
#define ONE						 1
#define TWO						 2

/* Function prototypes section*/
void RTOS_task1Handler(void);
void RTOS_task2Handler(void);
void RTOS_task3Handler(void);
void RTOS_task4Handler(void);

void RTOS_initSystickTimer(uint32_t tick_hz);
__attribute__((naked)) void RTOS_initSchedulerStack(uint32_t sched_top_of_stack);
void RTOS_initTasksStack(void);
void RTOS_initTaskControlBlock(void);
void RTOS_enableProcessorFaults(void);
__attribute__((naked)) void RTOS_switchToPsp(void);
uint32_t RTOS_getPspValue(void);
void RTOS_setPspValue(uint32_t currentPspAddress);
void RTOS_updateNextTask(void);
void RTOS_updateGlobalTickCount(void);
void RTOS_taskDelay(uint32_t tickCount);
void RTOS_unblockTasks(void);
void RTOS_schedule(void);
void RTOS_idleTask(void);

/* Typedef section */
typedef struct
{
	uint32_t 	pspValue;
	uint32_t 	blockCount;
	uint8_t  	currentState;
	void 		(*taskHandler)(void);
}TaskControlBlock_t;

typedef enum
{
	IDLE_TASK = 0,
	TASK_ONE,
	TASK_TWO,
	TASK_THREE,
	TASK_FOUR,
	MAX_TASKS
}ListsOfTasks_t;

/* Global variables section */
TaskControlBlock_t userTasks[MAX_TASKS];
uint8_t currentTask = TASK_ONE;
uint32_t globalTickCount = 0;

int main(void)
{
	RTOS_enableProcessorFaults();
	RTOS_initSchedulerStack(SCHED_STACK_START);
	RTOS_initTaskControlBlock();
	RTOS_initTasksStack();
	LED_initAll();
	RTOS_initSystickTimer(TICK_HZ);
	RTOS_switchToPsp();
	/* Start from first task */
	RTOS_task1Handler();
	for(;;);
}

void RTOS_idleTask(void)
{
	while(1);
}

void RTOS_task1Handler(void)
{
	while(1)
	{
		LED_setOn(LED_GREEN);
		RTOS_taskDelay(DELAY_COUNT_1S);
		LED_setOff(LED_GREEN);
		RTOS_taskDelay(DELAY_COUNT_1S);
	}
}

void RTOS_task2Handler(void)
{
	while(1)
	{
		LED_setOn(LED_ORANGE);
		RTOS_taskDelay(DELAY_COUNT_500MS);
		LED_setOff(LED_ORANGE);
		RTOS_taskDelay(DELAY_COUNT_500MS);
	}
}

void RTOS_task3Handler(void)
{
	while(1)
	{
		LED_setOn(LED_BLUE);
		RTOS_taskDelay(DELAY_COUNT_250MS);
		LED_setOff(LED_BLUE);
		RTOS_taskDelay(DELAY_COUNT_250MS);
	}
}

void RTOS_task4Handler(void)
{
	while(1)
	{
		LED_setOn(LED_RED);
		RTOS_taskDelay(DELAY_COUNT_125MS);
		LED_setOff(LED_RED);
		RTOS_taskDelay(DELAY_COUNT_125MS);
	}
}

void RTOS_initSystickTimer(uint32_t tick_hz)
{
	uint32_t *pSRVR = (uint32_t*)0xE000E014;
	uint32_t *pSCSR = (uint32_t*)0xE000E010;
    /* Calculation of reload value */
    uint32_t count_value = (SYSTICK_TIM_CLK/tick_hz) - 1;
    /* Clear the value of SVR */
    *pSRVR &= ~(0x00FFFFFFFF);
    /* Load the value in to SVR */
    *pSRVR |= count_value;
    /* Enable SysTick exception request */
    *pSCSR |= ( 1 << ONE);
    /* Indicate the clock source: processor clock source */
    *pSCSR |= ( 1 << TWO);
    /* Enable the counter */
    *pSCSR |= ( 1 << ZERO);
}

__attribute__((naked)) void RTOS_initSchedulerStack(uint32_t schedTopOfStack)
{
     __asm volatile("MSR MSP,%0": :  "r" (schedTopOfStack)  :   );
     __asm volatile("BX LR");
}

uint32_t RTOS_getPspValue(void)
{
	return userTasks[currentTask].pspValue;
}

void RTOS_setPspValue(uint32_t currentPspAddress)
{
	userTasks[currentTask].pspValue = currentPspAddress;
}

void RTOS_updateNextTask(void)
{
	uint8_t currentState = TASK_BLOCKED_STATE;
	for(uint8_t iTask = 0; iTask < MAX_TASKS; iTask++)
	{
		currentTask++;
		currentTask %= MAX_TASKS;
		currentState = userTasks[currentTask].currentState;
		if(currentState == TASK_RUNNING_STATE && currentTask != IDLE_TASK)
		{
			break;
		}
	}
	if(currentState == TASK_BLOCKED_STATE)
	{
		currentTask = IDLE_TASK;
	}
}

__attribute__((naked)) void RTOS_switchToPsp(void)
{
	/* Save original LR */
	__asm volatile("PUSH {LR}");
	__asm volatile("BL RTOS_getPspValue");
	__asm volatile("MSR PSP, R0");
	__asm volatile("POP {LR}");
	/* Make PSP as default SP */
	__asm volatile("MOV R0, #0X02");
	__asm volatile("MSR CONTROL, R0");
	__asm volatile("BX LR");
}

void RTOS_initTaskControlBlock(void)
{
	/* Set the initial state of each task */
	userTasks[IDLE_TASK].currentState = TASK_RUNNING_STATE;
	userTasks[TASK_ONE].currentState = TASK_RUNNING_STATE;
	userTasks[TASK_TWO].currentState = TASK_RUNNING_STATE;
	userTasks[TASK_THREE].currentState = TASK_RUNNING_STATE;
	userTasks[TASK_FOUR].currentState = TASK_RUNNING_STATE;
	/* Set the initial PC of each task */
	userTasks[IDLE_TASK].taskHandler = RTOS_idleTask;
	userTasks[TASK_ONE].taskHandler = RTOS_task1Handler;
	userTasks[TASK_TWO].taskHandler = RTOS_task2Handler;
	userTasks[TASK_THREE].taskHandler = RTOS_task3Handler;
	userTasks[TASK_FOUR].taskHandler = RTOS_task4Handler;
	/* Set the initial PSP value of each task */
	userTasks[IDLE_TASK].pspValue = IDLE_STACK_START;
	userTasks[TASK_ONE].pspValue = T1_STACK_START;
	userTasks[TASK_TWO].pspValue = T2_STACK_START;
	userTasks[TASK_THREE].pspValue = T3_STACK_START;
	userTasks[TASK_FOUR].pspValue = T4_STACK_START;
}

void RTOS_initTasksStack(void)
{
	uint32_t* pPSP;
	for (uint8_t iTask = 0; iTask < MAX_TASKS; iTask++)
	{
		pPSP = (uint32_t*) userTasks[iTask].pspValue;
		/* Stack model full descending */
		pPSP--;
		*pPSP = XPSR_VALUE;
		pPSP--;
		*pPSP = (uint32_t) userTasks[iTask].taskHandler;
		pPSP--;
		*pPSP = LR_VALUE;
		for (uint8_t iRx = 0; iRx < MAX_CORE_REGISTERS; iRx++)
		{
			pPSP--;
			*pPSP = RX_DUMMY_FRAME_VALUE;
		}
		/* Store the final value of PSP for each task to return them later */
		userTasks[iTask].pspValue = (uint32_t)pPSP;
	}
}

void RTOS_schedule(void)
{
	uint32_t* pICSR = (uint32_t*)0xE000ED04;
	*pICSR |= 1 << PENDSVSET;
}

void RTOS_taskDelay(uint32_t tickCount)
{
	INTERRUPT_DISABLE();
	if(currentTask != IDLE_TASK)
	{
		userTasks[currentTask].blockCount = globalTickCount + tickCount;
		userTasks[currentTask].currentState = TASK_BLOCKED_STATE;
		RTOS_schedule();
	}
	INTERRUPT_ENABLE();
}

void RTOS_updateGlobalTickCount(void)
{
	globalTickCount++;
}

void RTOS_unblockTasks(void)
{
	for(uint8_t iTask = TASK_ONE; iTask < MAX_TASKS; iTask++)
	{
		if(userTasks[iTask].currentState != TASK_RUNNING_STATE)
		{
			if(userTasks[iTask].blockCount == globalTickCount)
			{
				userTasks[iTask].currentState = TASK_RUNNING_STATE;
			}
		}
	}
}

void SysTick_Handler(void)
{
	uint32_t *pICSR = (uint32_t*)0xE000ED04;
	RTOS_updateGlobalTickCount();
	RTOS_unblockTasks();
	*pICSR |= 1 << PENDSVSET;
}

__attribute__((naked)) void PendSV_Handler(void)
{
	/* Save the context of current task */
	__asm volatile("MRS R0, PSP");
	__asm volatile("STMDB R0!, {R4-R11}");
	/* Save original LR */
	__asm volatile("PUSH {LR}");
	__asm volatile("BL RTOS_setPspValue");
	/* Retrieve the context of next task */
	__asm volatile("BL RTOS_updateNextTask");
	__asm volatile("BL RTOS_getPspValue");
	__asm volatile("LDMIA R0!, {R4-R11}");
	__asm volatile("MSR PSP, R0");
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");
}

void RTOS_enableProcessorFaults(void)
{
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;
	*pSHCSR |= ( 1 << MEMFAULTENA);
	*pSHCSR |= ( 1 << BUSFAULTENA);
	*pSHCSR |= ( 1 << USGFAULTENA);
}

void HardFault_Handler(void)
{
	printf("Exception : Hardfault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
	while(1);
}
